Repository redis/node-redis, pull requests merged in 2022-10, with the labels that each got.

#2239 Update RedisGraph README.md
  packages/graph/README.md
Labels: Documentation

#2278 Fixes typo Redis Search -> RediSearch
  README.md
Labels: Documentation, hacktoberfest-accepted

#2279 Fixed redis -> Redis in a couple places.
  docs/clustering.md
Labels: hacktoberfest-accepted
